name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Create and activate venv
      run: python -m venv .venv
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analyse the code with pylint
      run: |
        source .venv/bin/activate
        pylint $(git ls-files '*.py')
